<html>
<head>
<title>Détail de la correction.</title>
<style>
p.titre {font-weight: bold; font-family: Arial; font-size: 14pt;}
span.titreTest {font-weight: bold; font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.verdictTest {font-family: Arial; font-size: 12pt;}
span.titreException {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titreMessage {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titrePileAppel {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titreDiagnostic {font-family: Arial; font-size: 12pt; font-style: italic; color: #3300CC;}
span.pileAppel {font-family: Arial; font-size: 11pt;}
</style>
</head>
<body>
<p class="titre">Voici les tests qui ont posé des problèmes à votre exécutable. Cette liste est vide si tous se sont déroulés sans incident.</p>
<p><span class="titreTest">testBarkBankVerifyInvalidNumberCreditCard(s):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.net.SocketException</p>
<p><span class="titreMessage">Message        :</span> Unexpected end of file from server</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.net.SocketException: Unexpected end of file from server<br>	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)<br>	at java.security.AccessController.doPrivileged(Native Method)<br>	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)<br>	at com.meterware.httpunit.HttpWebResponse.readResponseHeader(HttpWebResponse.java:162)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:200)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:56)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:67)<br>	at com.meterware.httpunit.WebConversation.newResponse(WebConversation.java:76)<br>	at com.meterware.httpunit.WebWindow.getResource(WebWindow.java:164)<br>	at com.meterware.httpunit.WebWindow.getSubframeResponse(WebWindow.java:128)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:121)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:102)<br>	at com.meterware.httpunit.WebClient.getResponse(WebClient.java:87)<br>	at s.a(Unknown Source)<br>	at s.testBarkBankVerifyInvalidNumberCreditCard(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br>Caused by: java.net.SocketException: Unexpected end of file from server<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:2995)<br>	at com.meterware.httpunit.HttpWebResponse.loadHeaders(HttpWebResponse.java:216)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:198)<br>	... 27 more<br></span></p>
<p><span class="titreDiagnostic">testBarkBankVerifyInvalidNumberCreditCard(s): Unexpected end of file from server</span></p>
<br>
<p><span class="titreTest">testServiceVerifyValidCreditCard(N):</span> <span class="verdictTest">Le résultat que vous avez produit n'est pas celui attendu.</span></p>
<p><span class="titreDiagnostic">testServiceVerifyValidCreditCard(N): Credit card is valid. It should not throw an exception</span></p>
<br>
<p><span class="titreTest">testWebVisualiseCatalog(Y):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.net.SocketException</p>
<p><span class="titreMessage">Message        :</span> Unexpected end of file from server</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.net.SocketException: Unexpected end of file from server<br>	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)<br>	at java.security.AccessController.doPrivileged(Native Method)<br>	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)<br>	at com.meterware.httpunit.HttpWebResponse.readResponseHeader(HttpWebResponse.java:162)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:200)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:56)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:67)<br>	at com.meterware.httpunit.WebConversation.newResponse(WebConversation.java:76)<br>	at com.meterware.httpunit.WebWindow.getResource(WebWindow.java:164)<br>	at com.meterware.httpunit.WebWindow.getSubframeResponse(WebWindow.java:128)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:121)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:102)<br>	at com.meterware.httpunit.WebClient.getResponse(WebClient.java:87)<br>	at Y.testWebVisualiseCatalog(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br>Caused by: java.net.SocketException: Unexpected end of file from server<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:2995)<br>	at com.meterware.httpunit.HttpWebResponse.loadHeaders(HttpWebResponse.java:216)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:198)<br>	... 26 more<br></span></p>
<p><span class="titreDiagnostic">testWebVisualiseCatalog(Y): Unexpected end of file from server</span></p>
<br>
<p><span class="titreTest">testBarkBankVerifyInvalidXMLDocument(s):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.net.SocketException</p>
<p><span class="titreMessage">Message        :</span> Unexpected end of file from server</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.net.SocketException: Unexpected end of file from server<br>	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)<br>	at java.security.AccessController.doPrivileged(Native Method)<br>	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)<br>	at com.meterware.httpunit.HttpWebResponse.readResponseHeader(HttpWebResponse.java:162)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:200)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:56)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:67)<br>	at com.meterware.httpunit.WebConversation.newResponse(WebConversation.java:76)<br>	at com.meterware.httpunit.WebWindow.getResource(WebWindow.java:164)<br>	at com.meterware.httpunit.WebWindow.getSubframeResponse(WebWindow.java:128)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:121)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:102)<br>	at com.meterware.httpunit.WebClient.getResponse(WebClient.java:87)<br>	at s.a(Unknown Source)<br>	at s.testBarkBankVerifyInvalidXMLDocument(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br>Caused by: java.net.SocketException: Unexpected end of file from server<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:2995)<br>	at com.meterware.httpunit.HttpWebResponse.loadHeaders(HttpWebResponse.java:216)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:198)<br>	... 27 more<br></span></p>
<p><span class="titreDiagnostic">testBarkBankVerifyInvalidXMLDocument(s): Unexpected end of file from server</span></p>
<br>
<p><span class="titreTest">testDelegateFindAllCustomers(aF):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at com.yaps.petstore.common.delegate.CustomerDelegate.createCustomer(Unknown Source)<br>	at aF.a(Unknown Source)<br>	at aF.testDelegateFindAllCustomers(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testDelegateFindAllCustomers(aF): Invalid Card</span></p>
<br>
<p><span class="titreTest">testDelegateCreateCustomer(aF):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at com.yaps.petstore.common.delegate.CustomerDelegate.createCustomer(Unknown Source)<br>	at aF.a(Unknown Source)<br>	at aF.testDelegateCreateCustomer(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testDelegateCreateCustomer(aF): Invalid Card</span></p>
<br>
<p><span class="titreTest">testServiceFindAllCustomers(g):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at g.a(Unknown Source)<br>	at g.testServiceFindAllCustomers(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testServiceFindAllCustomers(g): Invalid Card</span></p>
<br>
<p><span class="titreTest">testDelegateCreateOrder(z):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.order.OrderService.createOrder(Unknown Source)<br>	at com.yaps.petstore.common.delegate.OrderDelegate.createOrder(Unknown Source)<br>	at z.a(Unknown Source)<br>	at z.testDelegateCreateOrder(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testDelegateCreateOrder(z): Invalid Card</span></p>
<br>
<p><span class="titreTest">testServiceCreateCustomer(g):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at g.a(Unknown Source)<br>	at g.testServiceCreateCustomer(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testServiceCreateCustomer(g): Invalid Card</span></p>
<br>
<p><span class="titreTest">testServiceUpdateCustomer(g):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at g.a(Unknown Source)<br>	at g.testServiceUpdateCustomer(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testServiceUpdateCustomer(g): Invalid Card</span></p>
<br>
<p><span class="titreTest">testBarkBankVerifyValidCreditCard(s):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.net.SocketException</p>
<p><span class="titreMessage">Message        :</span> Unexpected end of file from server</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.net.SocketException: Unexpected end of file from server<br>	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)<br>	at java.security.AccessController.doPrivileged(Native Method)<br>	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)<br>	at com.meterware.httpunit.HttpWebResponse.readResponseHeader(HttpWebResponse.java:162)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:200)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:56)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:67)<br>	at com.meterware.httpunit.WebConversation.newResponse(WebConversation.java:76)<br>	at com.meterware.httpunit.WebWindow.getResource(WebWindow.java:164)<br>	at com.meterware.httpunit.WebWindow.getSubframeResponse(WebWindow.java:128)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:121)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:102)<br>	at com.meterware.httpunit.WebClient.getResponse(WebClient.java:87)<br>	at s.a(Unknown Source)<br>	at s.testBarkBankVerifyValidCreditCard(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br>Caused by: java.net.SocketException: Unexpected end of file from server<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:2995)<br>	at com.meterware.httpunit.HttpWebResponse.loadHeaders(HttpWebResponse.java:216)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:198)<br>	... 27 more<br></span></p>
<p><span class="titreDiagnostic">testBarkBankVerifyValidCreditCard(s): Unexpected end of file from server</span></p>
<br>
<p><span class="titreTest">testWebCheckServlets(H):</span> <span class="verdictTest">Le résultat que vous avez produit n'est pas celui attendu.</span></p>
<p><span class="titreDiagnostic">testWebCheckServlets(H): The CreateCustomerServlet hasn't been found</span></p>
<br>
<p><span class="titreTest">testDelegateUpdateCustomerWithInvalidCreditCard(aF):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at com.yaps.petstore.common.delegate.CustomerDelegate.createCustomer(Unknown Source)<br>	at aF.a(Unknown Source)<br>	at aF.testDelegateUpdateCustomerWithInvalidCreditCard(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testDelegateUpdateCustomerWithInvalidCreditCard(aF): Invalid Card</span></p>
<br>
<p><span class="titreTest">testServletCreateCustomer(an):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.net.SocketException</p>
<p><span class="titreMessage">Message        :</span> Unexpected end of file from server</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.net.SocketException: Unexpected end of file from server<br>	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)<br>	at java.security.AccessController.doPrivileged(Native Method)<br>	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)<br>	at com.meterware.httpunit.HttpWebResponse.readResponseHeader(HttpWebResponse.java:162)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:200)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:56)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:67)<br>	at com.meterware.httpunit.WebConversation.newResponse(WebConversation.java:76)<br>	at com.meterware.httpunit.WebWindow.getResource(WebWindow.java:164)<br>	at com.meterware.httpunit.WebWindow.getSubframeResponse(WebWindow.java:128)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:121)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:102)<br>	at com.meterware.httpunit.WebClient.getResponse(WebClient.java:87)<br>	at an.a(Unknown Source)<br>	at an.testServletCreateCustomer(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br>Caused by: java.net.SocketException: Unexpected end of file from server<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:2995)<br>	at com.meterware.httpunit.HttpWebResponse.loadHeaders(HttpWebResponse.java:216)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:198)<br>	... 27 more<br></span></p>
<p><span class="titreDiagnostic">testServletCreateCustomer(an): Unexpected end of file from server</span></p>
<br>
<p><span class="titreTest">testDelegateUpdateCustomer(aF):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at com.yaps.petstore.common.delegate.CustomerDelegate.createCustomer(Unknown Source)<br>	at aF.a(Unknown Source)<br>	at aF.testDelegateUpdateCustomer(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testDelegateUpdateCustomer(aF): Invalid Card</span></p>
<br>
<p><span class="titreTest">testServiceUpdateCustomerWithInvalidCreditCard(g):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.customer.CustomerService.createCustomer(Unknown Source)<br>	at g.a(Unknown Source)<br>	at g.testServiceUpdateCustomerWithInvalidCreditCard(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testServiceUpdateCustomerWithInvalidCreditCard(g): Invalid Card</span></p>
<br>
<p><span class="titreTest">testServiceCreateOrder(am):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> com.yaps.petstore.common.exception.CheckException</p>
<p><span class="titreMessage">Message        :</span> Invalid Card</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">com.yaps.petstore.common.exception.CheckException: Invalid Card<br>	at com.yaps.petstore.server.service.creditcard.HTTPSender.send(Unknown Source)<br>	at com.yaps.petstore.server.service.creditcard.CreditCardService.verifyCreditCard(Unknown Source)<br>	at com.yaps.petstore.server.service.order.OrderService.createOrder(Unknown Source)<br>	at am.a(Unknown Source)<br>	at am.testServiceCreateOrder(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testServiceCreateOrder(am): Invalid Card</span></p>
<br>
<p><span class="titreTest">testBarkBankVerifyOldCreditCard(s):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.net.SocketException</p>
<p><span class="titreMessage">Message        :</span> Unexpected end of file from server</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.net.SocketException: Unexpected end of file from server<br>	at sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)<br>	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)<br>	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)<br>	at java.security.AccessController.doPrivileged(Native Method)<br>	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)<br>	at com.meterware.httpunit.HttpWebResponse.readResponseHeader(HttpWebResponse.java:162)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:200)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:56)<br>	at com.meterware.httpunit.HttpWebResponse.<init>(HttpWebResponse.java:67)<br>	at com.meterware.httpunit.WebConversation.newResponse(WebConversation.java:76)<br>	at com.meterware.httpunit.WebWindow.getResource(WebWindow.java:164)<br>	at com.meterware.httpunit.WebWindow.getSubframeResponse(WebWindow.java:128)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:121)<br>	at com.meterware.httpunit.WebWindow.getResponse(WebWindow.java:102)<br>	at com.meterware.httpunit.WebClient.getResponse(WebClient.java:87)<br>	at s.a(Unknown Source)<br>	at s.testBarkBankVerifyOldCreditCard(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:497)<br>	at junit.framework.TestCase.runTest(TestCase.java:168)<br>	at junit.framework.TestCase.runBare(TestCase.java:134)<br>	at junit.framework.TestResult$1.protect(TestResult.java:110)<br>	at junit.framework.TestResult.runProtected(TestResult.java:128)<br>	at junit.framework.TestResult.run(TestResult.java:113)<br>	at junit.framework.TestCase.run(TestCase.java:124)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:232)<br>	at junit.framework.TestSuite.run(TestSuite.java:227)<br>	at S.tester(Unknown Source)<br>	at S.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br>Caused by: java.net.SocketException: Unexpected end of file from server<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)<br>	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)<br>	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFieldKey(HttpURLConnection.java:2995)<br>	at com.meterware.httpunit.HttpWebResponse.loadHeaders(HttpWebResponse.java:216)<br>	at com.meterware.httpunit.HttpWebResponse.readHeaders(HttpWebResponse.java:198)<br>	... 27 more<br></span></p>
<p><span class="titreDiagnostic">testBarkBankVerifyOldCreditCard(s): Unexpected end of file from server</span></p>
<br>
<p><span class="titreTest">testWebCheckPages(H):</span> <span class="verdictTest">Le résultat que vous avez produit n'est pas celui attendu.</span></p>
<p><span class="titreDiagnostic">testWebCheckPages(H): Root http://localhost:8080/petstore hasn't been found</span></p>
<br>
</body>
</html>
